package com.psycodeinteractive.fbimostwanted.ui.feature.mostwantedperson

import com.psycodeinteractive.fbimostwanted.ui.screen.ScreenNavigationCallbacks

object MostWantedPersonScreenNavigationCallbacks : ScreenNavigationCallbacks
