package com.psycodeinteractive.fbimostwanted.presentation.feature.mostwantedlist

import com.psycodeinteractive.fbimostwanted.presentation.navigation.PresentationDestination

object MostWantedListPresentationDestination : PresentationDestination()
