package com.psycodeinteractive.fbimostwanted.domain.feature.mostwanted.model

import com.psycodeinteractive.fbimostwanted.domain.feature.mostwanted.model.SexDomainModel.Female
import com.psycodeinteractive.fbimostwanted.domain.feature.mostwanted.model.SexDomainModel.Male
import com.psycodeinteractive.fbimostwanted.domain.feature.mostwanted.model.StatusDomainModel.Captured
import com.psycodeinteractive.fbimostwanted.domain.feature.mostwanted.model.StatusDomainModel.Recovered

val givenMostWantedPerson1 = MostWantedPersonDomainModel(
    uid = "1",
    id = "1",
    rewardText = "reward",
    aliases = listOf("alias1", "alias2"),
    publication = "publication",
    url = "url",
    warningMessage = "warningMessage",
    details = "details",
    occupations = listOf("occupation1", "occupdation2"),
    nationality = "nationality",
    placeOfBirth = "placeOfBirth",
    datesOfBirthUsed = listOf("1", "2"),
    languages = listOf("pl", "en"),
    sex = Male,
    scarsAndMarks = "scarsAndMarks",
    complexion = "complexion",
    race = "race",
    raceRaw = "raceRaw",
    build = "build",
    hair = "hair",
    hairRaw = "hairRaw",
    eyes = "eyes",
    eyesRaw = "eyesRaw",
    ageMin = 20,
    ageMax = 50,
    ageRange = "20-50",
    weight = "weight",
    weightMin = 35,
    weightMax = 200,
    heightMin = 40,
    heightMax = 250,
    rewardMin = 0,
    rewardMax = 100000000,
    files = emptyList(),
    images = emptyList(),
    title = "Title",
    description = "Description",
    status = Recovered,
    remarks = "remarks",
    path = "path",
    possibleStates = listOf("CA", "NY"),
    possibleCountries = listOf("USA", "PL"),
    caution = "caution",
    modified = "modified",
    subjects = listOf("murder", "gta"),
    ncic = "ncic",
    fieldOffices = emptyList()
)

val givenMostWantedPerson2 = MostWantedPersonDomainModel(
    uid = "2",
    id = "2",
    rewardText = "reward",
    aliases = listOf("alias1", "alias2"),
    publication = "publication",
    url = "url",
    warningMessage = "warningMessage",
    details = "details",
    occupations = listOf("occupation1", "occupdation2"),
    nationality = "nationality",
    placeOfBirth = "placeOfBirth",
    datesOfBirthUsed = listOf("1", "2"),
    languages = listOf("pl", "en"),
    sex = Female,
    scarsAndMarks = "scarsAndMarks",
    complexion = "complexion",
    race = "race",
    raceRaw = "raceRaw",
    build = "build",
    hair = "hair",
    hairRaw = "hairRaw",
    eyes = "eyes",
    eyesRaw = "eyesRaw",
    ageMin = 30,
    ageMax = 40,
    ageRange = "30-40",
    weight = "weight",
    weightMin = 35,
    weightMax = 200,
    heightMin = 40,
    heightMax = 250,
    rewardMin = 0,
    rewardMax = 100000000,
    files = emptyList(),
    images = emptyList(),
    title = "Title",
    description = "Description",
    status = Captured,
    remarks = "remarks",
    path = "path",
    possibleStates = listOf("OH", "TX"),
    possibleCountries = listOf("USA", "PL"),
    caution = "caution",
    modified = "modified",
    subjects = listOf("murder", "gta"),
    ncic = "ncic",
    fieldOffices = emptyList()
)

val givenMostWantedList = listOf(
    givenMostWantedPerson1,
    givenMostWantedPerson2
)
