package com.psycodeinteractive.fbimostwanted.presentation.feature.mostwantedlist

import com.psycodeinteractive.fbimostwanted.presentation.navigation.PresentationDestination

sealed class MostWantedListPresentationDestination : PresentationDestination()
